### ISSUE TITLE
Error while installing Dependencies

### ISSUE THREAD

**Issue by patrick-steve** [BootstrapDash/corona-react-free-admin-template#3]
Got the following error while using `npm install`

`npm ERR! code 1
npm ERR! path E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'E:\\react-templates\\corona-react-free-admin-template-main\\corona-react-free-admin-template-main\\template\\demo_1\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.2.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:387:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\react-templates\\corona-react-free-admin-template-main\\corona-react-free-admin-template-main\\template\\demo_1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd E:\react-templates\corona-react-free-admin-template-main\corona-react-free-admin-template-main\template\demo_1\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1`

**Comment by SH-Stark** [comment]
You have to update the node-sass version to match your node version.

| NodeJS  | Supported node-sass version | Node Module |
|---------|-----------------------------|-------------|
| Node 16 | 6.0+                        | 93          |
| Node 15 | 5.0+                        | 88          |
| Node 14 | 4.14+                       | 83          |
| Node 13 | 4.13+, <5.0                 | 79          |
| Node 12 | 4.12+                       | 72          |
| Node 11 | 4.10+, <5.0                 | 67          |
| Node 10 | 4.9+, <6.0                  | 64          |
| Node 8  | 4.5.3+, <5.0                | 57          |
| Node <8 | <5.0                        | <57         |

**Comment by patrick-steve** [comment]
Can I use Sass instead?

**Comment by patrick-steve** [comment]
@SH-Stark Thank you for your response. Now the issue is solved!
